# Generated by Django 6.0.3 on 2026-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], max_length=10)),
                ('price', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rooms/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
