# Generated by Django 6.0.3 on 2026-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('4_sharing', '4 Sharing'), ('5_sharing', '5 Sharing')], max_length=15),
        ),
    ]
